- create
- delete
- destroy
- favorites
- followers
- followings
- get
- index
- name
- patch
- post
- registrations
- relationships
- search
- settings
- show
- subscribe
- tags
- themes
- timeline
- unsubscribe
- update
- user
- users
- withdrawal